# SPDX-FileCopyrightText: Copyright (c) 2012-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
name: pdd
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pdd:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: g4s8/pdd-action@master
